import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireSuperAdmin } from "@/lib/services/auth/session";
import { getGenerationProviders, getPlatformAIConfigs } from "@/lib/services/ai";
import { isEncryptionConfigured } from "@/lib/security/crypto";
import { getAppUrl } from "@/lib/appUrl";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

/**
 * Live system check.
 *
 * Every subsystem here has a fallback that keeps the app running when the real
 * thing is unavailable: AI drops to a keyword template, email drops to a
 * console recorder, uploads refuse politely. Those fallbacks are what makes
 * the product resilient, and also what makes a broken integration invisible --
 * a flow generated from a template looks like a flow generated by a model.
 *
 * So this actively exercises each one rather than reading configuration:
 * a real completion request, a real SMTP handshake, a real database query.
 */

type Status = "ok" | "warn" | "fail";

interface Check {
  key: string;
  label: string;
  status: Status;
  detail: string;
  hint?: string;
  ms?: number;
}

async function timed<T>(fn: () => Promise<T>): Promise<{ value?: T; error?: any; ms: number }> {
  const started = Date.now();
  try {
    return { value: await fn(), ms: Date.now() - started };
  } catch (error) {
    return { error, ms: Date.now() - started };
  }
}

async function checkDatabase(): Promise<Check> {
  const { error, ms } = await timed(() => prisma.$queryRaw`SELECT 1`);
  return {
    key: "database",
    label: "Database",
    status: error ? "fail" : "ok",
    detail: error ? "Could not reach the database." : `Connected in ${ms} ms.`,
    hint: error ? "Check DATABASE_URL in Vercel, and that the Neon project is not suspended." : undefined,
    ms,
  };
}

/** Sends a real, tiny completion to each configured provider. */
async function checkAi(): Promise<Check[]> {
  const providers = getGenerationProviders(null);

  if (providers.length === 0) {
    return [
      {
        key: "ai",
        label: "AI providers",
        status: "warn",
        detail: "No AI provider configured. Flow generation uses the keyword template.",
        hint: "Set AI_PROVIDER and AI_API_KEY. A free Gemini key: https://aistudio.google.com/apikey",
      },
    ];
  }

  const results = await Promise.all(
    providers.map(async (provider) => {
      const { value, error, ms } = await timed(() =>
        provider.complete({
          system: "Reply with a JSON object.",
          user: 'Return exactly {"ok":true}',
          temperature: 0,
          json: true,
        }),
      );

      const replied = typeof value === "string" && value.includes("ok");
      return {
        key: `ai:${provider.providerName}`,
        label: `AI · ${provider.providerName}`,
        status: (error ? "fail" : replied ? "ok" : "warn") as Status,
        detail: error
          ? String(error?.message || error).slice(0, 200)
          : replied
            ? `Responded in ${ms} ms.`
            : "Responded, but the reply was not usable.",
        hint: error ? "Free tiers shed load at peak times. A second provider keeps generation working." : undefined,
        ms,
      };
    }),
  );

  // One working provider is enough, so a busy backup is informational.
  if (results.some((result) => result.status === "ok")) {
    return results.map((result) => (result.status === "fail" ? { ...result, status: "warn" as Status } : result));
  }
  return results;
}

function checkStorage(): Check {
  const mode = (process.env.STORAGE_PROVIDER || process.env.STORAGE_MODE || "").toLowerCase();
  const hasToken = Boolean(process.env.BLOB_READ_WRITE_TOKEN);

  if (mode === "blob" || (!mode && hasToken)) {
    return {
      key: "storage",
      label: "File storage",
      status: hasToken ? "ok" : "fail",
      detail: hasToken ? "Blob store connected." : "Set to Blob, but no access token is present.",
      hint: hasToken ? undefined : "Vercel dashboard → Storage → Blob → Create, then connect it to this project.",
    };
  }

  return {
    key: "storage",
    label: "File storage",
    status: "fail",
    detail: `Storage is "${mode || "unset"}", which cannot work on a serverless deployment.`,
    hint: 'Set STORAGE_PROVIDER="blob" and connect a Blob store.',
  };
}

/** Opens a real SMTP connection and authenticates. */
async function checkEmail(): Promise<Check> {
  const provider = (process.env.EMAIL_PROVIDER || "console").toLowerCase();

  if (provider !== "smtp") {
    return {
      key: "email",
      label: "Email delivery",
      status: "warn",
      detail: "Emails are recorded to the server log, not delivered.",
      hint: 'Set EMAIL_PROVIDER="smtp" with SMTP_USER and SMTP_PASSWORD to send password-reset emails.',
    };
  }

  if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASSWORD) {
    return {
      key: "email",
      label: "Email delivery",
      status: "fail",
      detail: "SMTP is selected but the host, user or password is missing, so nothing is delivered.",
      hint: "For Gmail, create an App Password (not your account password) and set it as SMTP_PASSWORD.",
    };
  }

  const { error, ms } = await timed(async () => {
    const nodemailer = await import("nodemailer");
    const transport = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT || 587),
      secure: process.env.SMTP_PORT === "465",
      auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASSWORD },
      connectionTimeout: 10_000,
    });
    // Connects and authenticates without sending anything.
    await transport.verify();
  });

  return {
    key: "email",
    label: "Email delivery",
    status: error ? "fail" : "ok",
    detail: error
      ? String((error as any)?.message || error).slice(0, 200)
      : `SMTP authenticated in ${ms} ms.`,
    hint: error
      ? "Gmail rejects normal account passwords. Use an App Password, with 2-Step Verification enabled."
      : undefined,
    ms,
  };
}

function checkConfig(): Check[] {
  const appUrl = getAppUrl();
  const checks: Check[] = [
    {
      key: "app_url",
      label: "Public address",
      status: appUrl && !appUrl.includes("localhost") ? "ok" : "fail",
      detail: appUrl ? appUrl : "Not configured.",
      hint:
        appUrl && !appUrl.includes("localhost")
          ? undefined
          : "Set APP_URL to your live address, or password-reset and tracking links will point at the wrong host.",
    },
    {
      key: "encryption",
      label: "Secret encryption",
      status: isEncryptionConfigured() ? "ok" : "warn",
      detail: isEncryptionConfigured()
        ? "AI keys and SMTP passwords are encrypted at rest."
        : "Stored unencrypted.",
      hint: isEncryptionConfigured() ? undefined : "Set ENCRYPTION_KEY (openssl rand -hex 32).",
    },
  ];

  const configured = getPlatformAIConfigs();
  if (configured.length === 1 && configured[0].provider !== "ollama") {
    checks.push({
      key: "ai_backup",
      label: "AI backup provider",
      status: "warn",
      detail: "Only one AI provider is configured.",
      hint:
        "Free tiers go busy. Add GROQ_API_KEY (https://console.groq.com/keys) so generation falls back instead of " +
        "silently producing a template flow.",
    });
  }

  return checks;
}

export async function GET(_req: NextRequest) {
  try {
    await requireSuperAdmin();

    const [database, ai, email] = await Promise.all([checkDatabase(), checkAi(), checkEmail()]);
    const checks: Check[] = [database, ...ai, checkStorage(), email, ...checkConfig()];

    const summary = {
      ok: checks.filter((check) => check.status === "ok").length,
      warn: checks.filter((check) => check.status === "warn").length,
      fail: checks.filter((check) => check.status === "fail").length,
    };
    const data = { checks, summary, checkedAt: new Date().toISOString() };

    return NextResponse.json({ success: true, data, ...data });
  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: { code: "FORBIDDEN", message: error?.message || "Super Admin access required." } },
      { status: 403 },
    );
  }
}
