"use client";

import { useCallback, useEffect, useState } from "react";
import { Globe, Check, AlertTriangle, Copy, RefreshCw, Trash2, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";

interface DnsRecord {
  type: string;
  name: string;
  value: string;
  note?: string;
}

interface DomainState {
  slug: string;
  customDomain: string | null;
  verifiedAt: string | null;
  platformUrl: string;
  customUrl: string | null;
  dns: { domain: string; isApex: boolean; records: DnsRecord[]; platformStep: string } | null;
}

/**
 * Connects a workspace's own hostname to its chat, e.g. chat.acme.com.
 *
 * The DNS records shown here are generated by the server from the domain the
 * user entered, because a subdomain needs a CNAME and an apex domain cannot
 * use one — showing a single generic example would send half of users down the
 * wrong path.
 */
export function CustomDomainPanel() {
  const [state, setState] = useState<DomainState | null>(null);
  const [domainInput, setDomainInput] = useState("");
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [message, setMessage] = useState<{ tone: "ok" | "warn" | "error"; text: string } | null>(null);
  const [copied, setCopied] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/client/settings/domain");
      const json = await res.json();
      if (json.success) {
        const data = json.data || json;
        setState(data);
        setDomainInput(data.customDomain || "");
      }
    } catch {
      setMessage({ tone: "error", text: "Could not load domain settings." });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    setSaving(true);
    setMessage(null);
    try {
      const res = await fetch("/api/client/settings/domain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ domain: domainInput }),
      });
      const json = await res.json();
      if (!json.success) {
        setMessage({ tone: "error", text: json.error?.message || "Could not save the domain." });
        return;
      }
      setState(json.data || json);
      setMessage({ tone: "warn", text: "Domain saved. Create the DNS record below, then verify." });
    } catch {
      setMessage({ tone: "error", text: "Could not save the domain." });
    } finally {
      setSaving(false);
    }
  };

  const verify = async () => {
    setVerifying(true);
    setMessage(null);
    try {
      const res = await fetch("/api/client/settings/domain", { method: "PATCH" });
      const json = await res.json();
      const data = json.data || json;
      if (json.success && data.verified) {
        setMessage({ tone: "ok", text: data.message });
      } else {
        setMessage({ tone: "warn", text: data.message || json.error?.message || "Not reachable yet." });
      }
      await load();
    } catch {
      setMessage({ tone: "error", text: "Verification request failed." });
    } finally {
      setVerifying(false);
    }
  };

  const remove = async () => {
    if (!confirm("Disconnect this domain? The chat will still be reachable at its platform link.")) return;
    setSaving(true);
    try {
      await fetch("/api/client/settings/domain", { method: "DELETE" });
      setDomainInput("");
      setMessage({ tone: "ok", text: "Domain disconnected." });
      await load();
    } finally {
      setSaving(false);
    }
  };

  const copy = async (value: string, key: string) => {
    await navigator.clipboard.writeText(value);
    setCopied(key);
    setTimeout(() => setCopied(null), 1500);
  };

  if (loading) {
    return <Card><div className="p-6 text-sm text-slate-500">Loading domain settings…</div></Card>;
  }

  const isVerified = Boolean(state?.verifiedAt);

  return (
    <div className="space-y-4 animate-fade-in">
      <Card>
        <div className="p-5 space-y-4">
          <div className="flex items-start gap-3">
            <div className="w-9 h-9 rounded-xl bg-indigo-50 flex items-center justify-center shrink-0">
              <Globe className="w-4.5 h-4.5 text-indigo-600" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">Custom chat domain</h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Serve your chatbot from your own hostname, such as{" "}
                <code className="px-1 py-0.5 rounded bg-slate-100 text-slate-700">chat.yourcompany.com</code>, instead of
                the platform link.
              </p>
            </div>
          </div>

          <div className="rounded-xl border border-slate-200 bg-slate-50 p-3">
            <p className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-1">Current chat link</p>
            <div className="flex items-center gap-2 flex-wrap">
              <a
                href={state?.customUrl && isVerified ? state.customUrl : state?.platformUrl}
                target="_blank"
                rel="noreferrer"
                className="text-sm font-semibold text-indigo-700 hover:underline break-all"
              >
                {state?.customUrl && isVerified ? state.customUrl : state?.platformUrl}
              </a>
              <ExternalLink className="w-3.5 h-3.5 text-slate-400" />
            </div>
          </div>

          <form onSubmit={save} className="flex flex-col sm:flex-row gap-2">
            <input
              value={domainInput}
              onChange={(event) => setDomainInput(event.target.value)}
              placeholder="chat.yourcompany.com"
              className="flex-1 px-3 py-2 rounded-xl border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
            />
            <Button type="submit" disabled={saving || !domainInput.trim()} className="font-bold">
              {saving ? "Saving…" : state?.customDomain ? "Update domain" : "Connect domain"}
            </Button>
            {state?.customDomain && (
              <Button type="button" variant="outline" onClick={remove} disabled={saving} className="gap-1.5">
                <Trash2 className="w-3.5 h-3.5" />
                <span>Disconnect</span>
              </Button>
            )}
          </form>

          {message && (
            <div
              className={`flex items-start gap-2 rounded-xl px-3 py-2 text-xs font-medium ${
                message.tone === "ok"
                  ? "bg-emerald-50 text-emerald-800 border border-emerald-200"
                  : message.tone === "warn"
                    ? "bg-amber-50 text-amber-800 border border-amber-200"
                    : "bg-red-50 text-red-800 border border-red-200"
              }`}
            >
              {message.tone === "ok" ? (
                <Check className="w-3.5 h-3.5 mt-0.5 shrink-0" />
              ) : (
                <AlertTriangle className="w-3.5 h-3.5 mt-0.5 shrink-0" />
              )}
              <span>{message.text}</span>
            </div>
          )}
        </div>
      </Card>

      {state?.customDomain && state.dns && (
        <Card>
          <div className="p-5 space-y-4">
            <div className="flex items-center justify-between gap-3 flex-wrap">
              <div>
                <h3 className="text-sm font-bold text-slate-900">DNS records to create</h3>
                <p className="text-xs text-slate-500 mt-0.5">
                  Add these at your domain registrar or DNS provider (GoDaddy, Cloudflare, Route 53, and so on).
                </p>
              </div>
              <div className="flex items-center gap-2">
                <span
                  className={`px-2.5 py-1 rounded-full text-[11px] font-bold ${
                    isVerified ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"
                  }`}
                >
                  {isVerified ? "Live" : "Pending DNS"}
                </span>
                <Button size="sm" variant="outline" onClick={verify} disabled={verifying} className="gap-1.5 text-xs">
                  <RefreshCw className={`w-3.5 h-3.5 ${verifying ? "animate-spin" : ""}`} />
                  <span>{verifying ? "Checking…" : "Verify now"}</span>
                </Button>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-left text-[11px] uppercase tracking-wider text-slate-400 border-b border-slate-200">
                    <th className="py-2 pr-3 font-bold">Type</th>
                    <th className="py-2 pr-3 font-bold">Name / Host</th>
                    <th className="py-2 pr-3 font-bold">Value</th>
                    <th className="py-2 font-bold" />
                  </tr>
                </thead>
                <tbody>
                  {state.dns.records.map((record) => (
                    <tr key={record.type + record.name} className="border-b border-slate-100 align-top">
                      <td className="py-2.5 pr-3 font-mono font-bold text-slate-900">{record.type}</td>
                      <td className="py-2.5 pr-3 font-mono text-slate-700 break-all">{record.name}</td>
                      <td className="py-2.5 pr-3 font-mono text-slate-700 break-all">
                        {record.value}
                        {record.note && <p className="mt-1 font-sans text-[11px] text-slate-500">{record.note}</p>}
                      </td>
                      <td className="py-2.5">
                        <button
                          type="button"
                          onClick={() => copy(record.value, record.type + record.name)}
                          className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-500"
                          title="Copy value"
                        >
                          {copied === record.type + record.name ? (
                            <Check className="w-3.5 h-3.5 text-emerald-600" />
                          ) : (
                            <Copy className="w-3.5 h-3.5" />
                          )}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="rounded-xl border border-amber-200 bg-amber-50 p-3">
              <p className="text-xs font-bold text-amber-900 mb-1">One more step, on our side</p>
              <p className="text-xs text-amber-800">{state.dns.platformStep}</p>
              <p className="text-xs text-amber-800 mt-1.5">
                Send us <code className="px-1 rounded bg-amber-100">{state.customDomain}</code> so we can add it and
                issue the TLS certificate. Until that is done the browser will warn about the certificate even once DNS
                resolves.
              </p>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
}
